#title           :zabbix_server.yml
#description     :This ansible playbook will install zabbix monitoring system
#author          :Timur Bikbaev
#date            :20170718
#version         :0.2
#usage           :ansible-playbook zabbix_server.yml --ask-vault-pass --ask-sudo-pass
#notes           :create pass.yml with command "ansible-vault create pass.yml" , content "password: <password>"
#notes           :you need to change section "vars" accordingly
#ansible_version :2.3.1+
#requrements     :python ubuntu 14.04 php 5.6
#==============================================================================
---
- hosts: "{{ variable_host | default('192.168.88.138') }}"
  sudo: yes
  tasks:
  - name: attaching pass
    include_vars:
      file: pass.yml

#  - name: Install nginx and php-fpm
#    apt:
#      name: "{{ item }}"
#      state: latest
#    with_items:
#      - nginx
#      - php5-fpm
#    when: web is defined

  - name: Install apache
    apt: name=apache2 update_cache=yes state=latest
#    when: web is not defined

  - name: enabled apache mods
    apache2_module:
      name: "{{ item }}"
      state: present
    with_items:
      - rewrite
      - ssl
    notify:
      - restart apache2
#    when: web is not defined

  - name: Install MariaDB repository
    apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present

  - name: Add repository key to the system
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

  - name: mysql installation
    apt:
      name: "{{ item }}"
      state: latest
      force: yes
    with_items:
      - mariadb-server-10.0
      - mariadb-client-10.0
      - python-mysqldb


  - name: Update MySQL root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
 
  - name: Copy the root credentials as .my.cnf file
    template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost
      - "{{ ansible_hostname }}"

  - name: Remove the test database
    mysql_db: name=test state=absent
    notify:
      - Restart MySQL
  
  - name: Install Zabbix server
    apt:  
      deb: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-server-mysql_3.2.7-1+trusty_amd64.deb
      update_cache: yes

  - name: Install Zabbix frontend
    apt:
      deb: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-frontend-php_3.2.7-1+trusty_all.deb
      update_cache: yes
  
  - name: Copy frontend conf
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: 'zabbix.conf.php.j2', dest: '/usr/share/zabbix/conf/zabbix.conf.php' }
      - { src: 'apache.conf', dest: '/etc/zabbix/apache.conf' }
  
  - name: Frontend apache conf
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: '/etc/zabbix/apache.conf', dest: '/etc/apache2/conf-available/zabbix.conf' }
      - { src: '../conf-available/zabbix.conf', dest: '/etc/apache2/conf-enabled/zabbix.conf' }
    notify:
      - restart apache2

  - name: add timezone to php.ini
    replace:
      path: /etc/php5/apache2/php.ini
      regexp: '^;date.timezone ='
      replace: 'date.timezone = America/New_York'
      backup: no
    when: web is not defined

  - name: "MySQL | Create database"
    mysql_db: name=zabbix
      state=present
      encoding=utf8
      collation=utf8_bin
    register: db_created
 
  - name: Restore zabbix default database
    mysql_db:
      name: zabbix
      state: import
      target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
    when: db_created.changed

  - name: change Zabbix conf
    replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^DBUser=zabbix'
      replace: 'DBUser=root'
      backup: no

  - name: add DB pass to conf
    lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      insertafter: '^DBUser=root'
      line: 'DBPassword={{ mysql_root_pass }}'
  
  - name: Copy users dump file
    copy:
      src: users.sql
      dest: /tmp
    when: db_created.changed  

  - name: Restore zabbix default database
    mysql_db:
      name: zabbix
      state: import
      target: /tmp/users.sql
    when: db_created.changed

  - name: start zabbix-server
    service: name=zabbix-server state=started     
   
  - name: restart apache one more time
    service: name=apache2 state=restarted
   
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: Restart MySQL
      service: name=mysql state=restarted
